

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Personal extends javax.swing.JFrame {

   private byte[] person_image = null;
    
    ResultSet rs;
    Connection con;
    PreparedStatement ps;
    
    String url = "jdbc:mysql://localhost:3306/Personal_Information?";
    String username = "root";
    String password = "";
    
    private void checkEmployeeId() {
    String emplId = txtEmployee_Id.getText().trim(); // Trim spaces

    try {
        String url = "jdbc:mysql://localhost:3306/Personal_Information?";
        String user = "root";
        String password = "";
        con = DriverManager.getConnection(url, user, password);

        // Query Personal Information
        String queryPersonal = "SELECT * FROM personal_information WHERE employee_Id = ?";
        ps = con.prepareStatement(queryPersonal);
        ps.setString(1, emplId);
        rs = ps.executeQuery();

        if (rs.next()) {
            txtfirstName.setText(rs.getString("firstName"));
            txtmiddleName.setText(rs.getString("middleName"));
            txtlastName.setText(rs.getString("lastName"));
            txtemail.setText(rs.getString("email"));

            java.sql.Date birthdate = rs.getDate("birthdate");
            jdcbirthdate.setDate(birthdate != null ? birthdate : null);

            cmbage.setSelectedItem(String.valueOf(rs.getInt("age")));
            String gender = rs.getString("Sex");
            if ("Male".equalsIgnoreCase(gender)) {
                rbtnmale.setSelected(true);
            } else if ("Female".equalsIgnoreCase(gender)) {
                rbtnfemale.setSelected(true);
            }

            cbnationality.setSelectedItem(rs.getString("Nationality"));
            txtaddress.setText(rs.getString("address"));
            txtcontactNo.setText(rs.getString("ContactNo"));
            cmbCivilStatus.setSelectedItem(rs.getString("civilStatus"));
            cmbReligion.setSelectedItem(rs.getString("religion"));
            txtPagibig.setText(rs.getString("Pag_IBIG")); 
            txtPhilhealth.setText(rs.getString("PhilHealth"));
            txtTIN.setText(rs.getString("TIN"));
            Blob blob = rs.getBlob("photo");
       if (blob != null) {
              byte[] imageBytes = blob.getBytes(1, (int) blob.length());
          ImageIcon imageIcon = new ImageIcon(new ImageIcon(imageBytes).getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH));
       lblPhoto.setIcon(imageIcon);
     }
            btnprocess.setText("Update");
        } else {
        erase();
        }
    } catch (SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   private void erase() {
    btnprocess.setText("Add");
    txtfirstName.setText(null);
    txtmiddleName.setText(null);
    txtlastName.setText(null);
    txtemail.setText(null);
    jdcbirthdate.setDate(null);
    cmbage.setSelectedItem("Select Age");
    sexGroup.clearSelection();
    cmbCivilStatus.setSelectedIndex(0); // Reset Civil Status JComboBox
    cmbReligion.setSelectedIndex(0); // Reset Religion JComboBox
    txtaddress.setText(null);
    txtcontactNo.setText(null);
    txtPagibig.setText(null);
    txtPhilhealth.setText(null);
    txtTIN.setText(null);
    lblPhoto.setIcon(null); // Clear the displayed photo
    person_image = null; // Reset the image byte array
}

    
    public Personal() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        txtmiddleName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTIN = new javax.swing.JTextField();
        txtcontactNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPagibig = new javax.swing.JTextField();
        txtPhilhealth = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbage = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtEmployee_Id = new javax.swing.JTextField();
        cbnationality = new javax.swing.JComboBox<>();
        btnUploadPhoto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbCivilStatus = new javax.swing.JComboBox<>();
        cmbReligion = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jdcbirthdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        btnprocess = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 165, 15));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("First Name");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        txtfirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 190, -1));

        txtmiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmiddleNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtmiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 190, -1));

        jLabel4.setText("Middle Name");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel5.setText("Last Name");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, -1));

        txtlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 190, -1));

        jLabel6.setText("Date of Birth");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        sexGroup.add(rbtnmale);
        rbtnmale.setText("Male");
        rbtnmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, -1, -1));

        sexGroup.add(rbtnfemale);
        rbtnfemale.setText("Female");
        jPanel1.add(rbtnfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, -1, -1));

        jLabel8.setText("Age");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 190, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        jLabel10.setText("Civil Status");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        jLabel2.setText("Religion");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 60, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Nationality");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        txtTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTINActionPerformed(evt);
            }
        });
        jPanel1.add(txtTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 190, -1));

        txtcontactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Home Address");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel13.setText("Phone Number");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        jLabel14.setText("TIN");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, -1, -1));

        jLabel15.setText("Email Address");
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Pag-IBIG");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        txtPagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagibigActionPerformed(evt);
            }
        });
        jPanel1.add(txtPagibig, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 190, -1));

        txtPhilhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhilhealthActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhilhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 190, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("PhilHealth");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        cmbage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Age", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jPanel1.add(cmbage, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 140, -1));

        jPanel3.setBackground(new java.awt.Color(5, 165, 15));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setText("Personal Information");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 440, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1110, 40));

        jPanel4.setBackground(new java.awt.Color(5, 165, 15));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 40));

        jButton9.setText("Employment History");
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, 40));

        jButton7.setText("Personal Information");
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 40));

        jButton8.setText("Educational Background");
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 40));

        jButton5.setText("Statistical");
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 600));

        txtEmployee_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployee_IdKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmployee_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, -1));

        cbnationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "British", "Canadian", "Chinese", "Filipino\"", "French", "German", "Indian ", "Indonesian", "Italian", "Japanese", "Korean", "Mexican", "Russian", "Spanish ", "Thai", "Vietnamese ", "Australian\",", "Brazilian", "Egyptian", "Turkish", "South African" }));
        jPanel1.add(cbnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, -1));

        btnUploadPhoto.setText("Upload Photo");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel18.setText("Employee ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        cmbCivilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married ", "Divorced", "Widowed", "Separated", "Annulled " }));
        jPanel1.add(cmbCivilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 140, -1));

        cmbReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catholicism", "Christianity ", "Islam", "Protestantism", "Iglesia ni Cristo", "Buddhism", "Aglipayan (Philippine Independent Church)", "Hinduism", "Judaism", "Sikhism", "Bahá'í Faith", "Indigenous Religions (Anitism, Babaylan practices)", "Other", " " }));
        jPanel1.add(cmbReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 140, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel19.setText("TeaMS");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 170, 50));
        jPanel1.add(jdcbirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 180, -1));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 190, 50));

        btnprocess.setText("Add");
        btnprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocessActionPerformed(evt);
            }
        });
        jPanel1.add(btnprocess, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, 20));

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcontactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactNoActionPerformed

    private void txtTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTINActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void rbtnmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnmaleActionPerformed

    private void txtlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastNameActionPerformed

    private void txtmiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmiddleNameActionPerformed

    private void txtfirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstNameActionPerformed

    private void txtPagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagibigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagibigActionPerformed

    private void txtPhilhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhilhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhilhealthActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessActionPerformed
                                          
    // TODO add your handling code here:

    String emplId = txtEmployee_Id.getText();
    String fN = txtfirstName.getText();
    String mN = txtmiddleName.getText();
    String lN = txtlastName.getText();

    String sex = "";
    if (rbtnmale.isSelected()) {
        sex = "Male";
    } else if (rbtnfemale.isSelected()) {
        sex = "Female";
    }
    String age = cmbage.getSelectedItem().toString();
    String email = txtemail.getText();
    String contactNO = txtcontactNo.getText();
    String nationality = cbnationality.getSelectedItem().toString();
    String address = txtaddress.getText();
    String civilStatus = cmbCivilStatus.getSelectedItem().toString();
    String religion = cmbReligion.getSelectedItem().toString();
    String pagibig = txtPagibig.getText();
    String philhealth = txtPhilhealth.getText();
    String tin = txtTIN.getText();
    String sql;
    // **Validation for Employee ID**
    if (!emplId.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Employee ID must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // **Ensure all required fields are filled**
    if (emplId.isEmpty() || fN.isEmpty() || lN.isEmpty() || email.isEmpty() || contactNO.isEmpty() || nationality.isEmpty() || address.isEmpty() ||
        pagibig.isEmpty() || philhealth.isEmpty() || tin.isEmpty()) { // NEW: Checking Government IDs
        JOptionPane.showMessageDialog(null, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // **Validate Name Fields (Must contain only letters)**
    if (!fN.matches("[a-zA-Z]+") || !mN.matches("[a-zA-Z]*") || !lN.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(null, "Name fields must contain only letters!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // **Validate Contact Number (Must be digits)**
    if (!contactNO.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Contact number must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // **Validate PAG-IBIG, PhilHealth, and TIN (Must be digits)**
    if (!pagibig.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "PAG-IBIG number must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!philhealth.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "PhilHealth number must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!tin.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "TIN number must contain only digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // **Validate Birthdate**
    java.util.Date selectedDate = jdcbirthdate.getDate();
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(null, "Please select a birthdate!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop execution if no date is selected
    }

    java.sql.Date sqlBirthdate = new java.sql.Date(selectedDate.getTime());

    if (sex.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a gender!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        con = DriverManager.getConnection(url, username, password);
        ps = con.prepareStatement("SELECT * FROM Personal_Information");
        rs = ps.executeQuery();

        btnprocess.getText().equals("Add");

        // **Insert Query (Added PAG-IBIG, PhilHealth, and TIN)**
        sql = "INSERT INTO Personal_Information (Employee_Id, firstName, middleName, lastName, Birthdate, Age, Sex, Email, ContactNo, Nationality, Address, civilStatus, religion, Pag_IBIG, philhealth, TIN, photo) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        ps = con.prepareStatement(sql);
        ps.setString(1, emplId);
        ps.setString(2, fN);
        ps.setString(3, mN);
        ps.setString(4, lN);
        ps.setDate(5, sqlBirthdate);
        ps.setString(6, age);
        ps.setString(7, sex);
        ps.setString(8, email);
        ps.setString(9, contactNO);
        ps.setString(10, nationality);
        ps.setString(11, address);
        ps.setString(12, civilStatus);
        ps.setString(13, religion);
        ps.setString(14, pagibig);
        ps.setString(15, philhealth);
        ps.setString(16, tin);
        ps.setBytes(17, person_image);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Successfully added to records!!");
        erase();
        if (btnprocess.getText().equals("Update")) {
            // **Update Query (Added PAG-IBIG, PhilHealth, and TIN)**
            sql = "UPDATE Personal_Information SET firstName=?, middleName=?, lastName=?, Birthdate=?, Age=?, Sex=?, Email=?, ContactNo=?, Nationality=?, Address=?,civilStatus=?, religion=?, Pag_IBIG=?, philhealth=?, TIN=? WHERE Employee_Id=?";

            ps = con.prepareStatement(sql);
            ps.setString(1, fN);
            ps.setString(2, mN);
            ps.setString(3, lN);
            ps.setDate(4, sqlBirthdate);
            ps.setString(5, age);
            ps.setString(6, sex);
            ps.setString(7, email);
            ps.setString(8, contactNO);
            ps.setString(9, nationality);
            ps.setString(10, address);
            ps.setString(11, civilStatus);
            ps.setString(12, religion);
            ps.setString(13, pagibig);
            ps.setString(14, philhealth);
            ps.setString(15, tin);
            ps.setBytes(16, person_image);
            ps.setString(17, emplId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Successfully Updated!!");
            con.setAutoCommit(true);
            con.commit();
            erase();
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }


        
    }//GEN-LAST:event_btnprocessActionPerformed

    private void txtEmployee_IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployee_IdKeyReleased
        // TODO add your handling code here:
       checkEmployeeId();
    }//GEN-LAST:event_txtEmployee_IdKeyReleased

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);
    File file = chooser.getSelectedFile();
    
    if (file != null) {
        String filename = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH));
        lblPhoto.setIcon(icon);

        try {
            FileInputStream fis = new FileInputStream(file);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            int readNum;
            while ((readNum = fis.read(buf)) != -1) {
                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray(); // Convert image to bytes
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JButton btnprocess;
    private javax.swing.JComboBox<String> cbnationality;
    private javax.swing.JComboBox<String> cmbCivilStatus;
    private javax.swing.JComboBox<String> cmbReligion;
    private javax.swing.JComboBox<String> cmbage;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcbirthdate;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private javax.swing.ButtonGroup sexGroup;
    private javax.swing.JTextField txtEmployee_Id;
    private javax.swing.JTextField txtPagibig;
    private javax.swing.JTextField txtPhilhealth;
    private javax.swing.JTextField txtTIN;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontactNo;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    private javax.swing.JTextField txtmiddleName;
    // End of variables declaration//GEN-END:variables
}
